# Generated by Django 4.1.2 on 2022-10-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='imagePath',
            field=models.FilePathField(blank=True, path='main/images', verbose_name='ImagePath'),
        ),
    ]
