# Generated by Django 4.1.2 on 2022-10-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_employee_age_alter_employee_imagepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
    ]
